name: Build Windows EXE

on:
    workflow_dispatch:

jobs:
    build-windows:
        runs-on: windows-latest
        env:
            FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install customtkinter pynput opencv-python numpy mss requests gdown

            - name: Build EXE with PyInstaller
              shell: cmd
              run: |
                  pyinstaller --onedir --windowed PyWareFishingV4.py --name PyWareFishingV4 --icon="icon.ico" --add-data "ui;ui"

            - name: List dist contents
              run: |
                  echo "Files in dist folder:"
                  dir dist
                  echo "Size of executable:"
                  dir dist\PyWareFishingV4.exe

            - name: Upload EXE artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Windows-EXE
                  path: dist/PyWareFishingV4.exe
                  if-no-files-found: error